import os
import re
import pandas as pd

# Set directory path where CSV files are stored
csv_directory = "."
output_html_file = "lists.html"

# Read all CSV files in the directory
csv_files = [f for f in os.listdir(csv_directory) if f.endswith(".csv")]
books_data = []

# Process each CSV file
for csv_file in csv_files:
    file_path = os.path.join(csv_directory, csv_file)
    df = pd.read_csv(file_path)

    # Filter out rows where 'Book' is NaN before cleaning the 'Pages' column
    df = df.dropna(subset=["Book"])

    # Filter to include only rows where '?' column has 'X'
    df = df[df["?"] == "X"]

    # Remove commas from the Pages column and convert to integer where possible
    df["Pages"] = df["Pages"].astype(str).str.replace(",", "")
    df["Pages"] = pd.to_numeric(df["Pages"], errors="coerce").fillna(0).astype(int)

    # Extract relevant columns and filter out rows with missing data in 'Start'
    df = df[["Start", "End", "Book", "Author", "Pages"]].dropna(subset=["Start"])
    df["Start"] = pd.to_datetime(df["Start"], errors="coerce")  # Convert to datetime
    df["Year"] = df["Start"].dt.year  # Extract year

    # Add to the main list
    books_data.append(df)

# Concatenate all data and sort by year (newest to oldest) and start date within each year
books_df = pd.concat(books_data).sort_values(
    by=["Year", "Start"], ascending=[False, True]
)

# Build the per-year sections (Prairie reading-list markup) and tally totals
sections = []
years_meta = []  # (year, total_books, total_pages)
total_books_all = 0
total_pages_all = 0

for year, year_df in books_df.groupby("Year", sort=False):
    year = int(year)
    total_books = len(year_df)
    total_pages = int(year_df["Pages"].sum())
    total_books_all += total_books
    total_pages_all += total_pages
    years_meta.append((year, total_books, total_pages))

    items = ""
    for _, row in year_df.iterrows():
        title = row["Book"]
        # Normalize the author field only (titles are left untouched):
        # multi-author connectors -> comma, and "Ph.D." -> "PhD".
        author = str(row["Author"])
        author = re.sub(r"\s*&\s*", ", ", author)
        author = re.sub(r",?\s+and\s+", ", ", author)
        author = author.replace("Ph.D.", "PhD").replace("Ph.D", "PhD")
        pages = f"{int(row['Pages']):,}"  # Format pages with commas
        items += (
            f'        <li class="book"><span class="bk-title">{title}</span>'
            f'<span class="bk-author">{author}</span>'
            f'<span class="bk-pages">{pages}</span></li>\n'
        )

    sections.append(
        f'<section class="year-block" id="{year}">\n'
        f'      <div class="wrap">\n'
        f'        <div class="year-head">\n'
        f'          <h2 class="year-num">{year}</h2>\n'
        f'          <div class="year-stats"><span>{total_books:,} books</span>'
        f'<span>{total_pages:,} pages</span></div>\n'
        f'        </div>\n'
        f'        <ul class="book-list">\n{items}        </ul>\n'
        f'      </div>\n'
        f'    </section>'
    )

sections_html = "\n".join(sections)

# Build the reading-list meta (overall total + year-jump nav)
navpills = " ".join(f'<a href="#{y[0]}">{y[0]}</a>' for y in years_meta)
meta_html = (
    f'  <p class="reading-total"><strong>{total_books_all}</strong> books &middot; '
    f'<strong>{total_pages_all:,}</strong> pages</p>\n'
    f'  <nav class="year-nav" aria-label="Jump to year">{navpills}</nav>'
)

# Write the book sections to lists.html (kept for backwards compatibility)
with open(output_html_file, "w", encoding="utf-8") as f:
    f.write(sections_html)
print(f"Generated book lists in {output_html_file}")

# Inline the generated content into ../books.html between marker comments so
# the page is pre-rendered for SEO/crawlers without JS. Two managed regions:
#   BOOKS:START/END    -> the per-year book sections
#   READING:START/END  -> the overall total + year-jump nav
books_html_path = os.path.join("..", "books.html")
if os.path.exists(books_html_path):
    with open(books_html_path, "r", encoding="utf-8") as f:
        page = f.read()

    books_block = (
        "<!-- BOOKS:START (generated by reading/generate.py) -->\n"
        + sections_html
        + "\n<!-- BOOKS:END -->"
    )
    reading_block = "<!-- READING:START -->\n" + meta_html + "\n  <!-- READING:END -->"

    # Use lambda replacements so book titles can't be mistaken for backreferences.
    page, n_books = re.subn(
        r"<!-- BOOKS:START.*?BOOKS:END -->", lambda _: books_block, page, flags=re.DOTALL
    )
    page, n_reading = re.subn(
        r"<!-- READING:START.*?READING:END -->", lambda _: reading_block, page, flags=re.DOTALL
    )

    if n_books and n_reading:
        with open(books_html_path, "w", encoding="utf-8") as f:
            f.write(page)
        print(f"Inlined book lists + reading meta into {books_html_path}")
    else:
        print(
            f"Warning: markers not found (books={n_books}, reading={n_reading}) "
            f"in {books_html_path}"
        )
